#include "port_lcfg.h"
 Port_ConfigType STR_PortsConfig[PORT_PINS_NUMS] = { // Red LED // Blue LED
{PORT_MODE_DIGITAL, PORT_PIN_LEVEL_HIGH, PORT_PIN_DIRECTION_OUT, PORT_PIN_PUR, PORT_PIN_OUTPUT_CURRENT_8MA, PORTF,PIN_3,Port_pin}
//{PORT_MODE_DIGITAL, PORT_PIN_LEVEL_HIGH, PORT_PIN_DIRECTION_IN, PORT_PIN_PUR, PORT_PIN_OUTPUT_CURRENT_4MA, PORTF,PIN_4,Port_Int,IntSense_Edges,IntEvent_Falling,IntEvent_Masked}, // Green LED
};
