/*
 * EXT_INTERRUPT_Private.h
 *
 *  Created on: 9 Apr 2023
 *      Author: 20101
 */

#ifndef MCAL_INTERRUPT_EXTERNAL_INTERRUPT_EXT_INTERRUPT_PRIVATE_H_
#define MCAL_INTERRUPT_EXTERNAL_INTERRUPT_EXT_INTERRUPT_PRIVATE_H_

#define MCUCR_REG *(( VUchar8_t *)0x55)
#define MCUCSR_REG *(( VUchar8_t *)0x54)
#define GICR_REG *(( VUchar8_t *)0x5B)
#define GIFR_REG *(( VUchar8_t *)0x5A)



#endif /* MCAL_INTERRUPT_EXTERNAL_INTERRUPT_EXT_INTERRUPT_PRIVATE_H_ */
