/*
 * EXT_INTERRUPT_Config.h
 *
 *  Created on: 9 Apr 2023
 *      Author: 20101
 */

#ifndef MCAL_INTERRUPT_EXTERNAL_INTERRUPT_EXT_INTERRUPT_CONFIG_H_
#define MCAL_INTERRUPT_EXTERNAL_INTERRUPT_EXT_INTERRUPT_CONFIG_H_


typedef enum
{
	MCUCR_REG_ISC00_BITS = 0,
	MCUCR_REG_ISC01_BITS,
	MCUCR_REG_ISC10_BITS,
	MCUCR_REG_ISC11_BITS

}EN_MCUCR_REG_BITS;


typedef enum
{
	MCUCSR_REG_ISC2_BITS = 6,

}EN_MCUCSR_REG_BITS;

typedef enum
{
	GICR_REG_INT2_BITS = 5,
	GICR_REG_INT0_BITS,
	GICR_REG_INT1_BITS

}EN_GICR_REG_BITS;

typedef enum
{
	GIFR_REG_INTF2_BITS = 5,
	GIFR_REG_INTF0_BITS,
	GIFR_REG_INTF1_BITS

}EN_GIFR_REG_BITS;


typedef enum
{
	LOW_LEVEL_SENSE_CONTROL = 0,
	ANY_LOGICAL_SENSE_CONTROL,
	FALLING_EDGE_SENSE_CONTROL,
	RISING_EDGE_SENSE_CONTROL

}EN_EXT_INTERRUPT_Sense_Control;

typedef enum
{
	EXT0_INTERRUPTS = 0,
	EXT1_INTERRUPTS,
	EXT2_INTERRUPTS
}EN_EXT_INTERRUPTS;


typedef struct
{
	void(*INTERRUPT_EXTERNAL_HANDLER)(void);
	EN_EXT_INTERRUPTS EXTERNAL_INTERRUPRT_Number;
	EN_EXT_INTERRUPT_Sense_Control EXTERNAL_INTERRUPRT_Sense_Control;

}ST_EXT_INTERRUPTS_CFG;

#endif /* MCAL_INTERRUPT_EXTERNAL_INTERRUPT_EXT_INTERRUPT_CONFIG_H_ */
